import { type Tool, type ToolInput, type ToolResult } from "./registry.js";
import { writeFileTool } from "./writeFile.js";

interface GenerateJSInput {
  filename: string;
  code: string;
  strict?: boolean;
}

function isGenerateJSInput(input: unknown): input is GenerateJSInput {
  if (typeof input !== "object" || input === null) return false;
  const i = input as Record<string, unknown>;
  return typeof i["filename"] === "string" && typeof i["code"] === "string";
}

export const generateJSTool: Tool = {
  name: "generateJS",
  description: "Write JavaScript code to a file in the output directory.",
  inputSchema: {
    filename: {
      type: "string",
      description: "Output filename, e.g. app.js",
      required: true,
    },
    code: {
      type: "string",
      description: "The JavaScript source code to write.",
      required: true,
    },
    strict: {
      type: "boolean",
      description: 'Prepend "use strict" directive. Defaults to true.',
    },
  },

  async execute(raw: ToolInput): Promise<ToolResult> {
    if (!isGenerateJSInput(raw)) {
      return { success: false, error: "Missing required fields: filename, code" };
    }

    const input = raw as GenerateJSInput;
    const useStrict = input.strict !== false;
    const header = [
      `// Generated by AI Agent CLI — ${new Date().toISOString()}`,
      ...(useStrict ? ['"use strict";', ""] : [""]),
    ].join("\n");

    return writeFileTool.execute({
      filePath: input.filename,
      content: header + input.code,
    });
  },
};
