import { type Tool, type ToolInput, type ToolResult } from "./registry.js";
import { writeFileTool } from "./writeFile.js";

interface GenerateCSSInput {
  filename: string;
  rules?: string;
}

function isGenerateCSSInput(input: unknown): input is GenerateCSSInput {
  if (typeof input !== "object" || input === null) return false;
  const i = input as Record<string, unknown>;
  return typeof i["filename"] === "string";
}

function buildPremiumCSS(extraRules: string): string {
  return `/* Generated by AI Agent CLI — ${new Date().toISOString()} */

/* ============================================================
   CSS VARIABLES — Design tokens
   ============================================================ */
:root {
  /* Colors */
  --color-primary:        #FF6B35;
  --color-primary-dark:   #e55a24;
  --color-primary-light:  #ff8c5a;
  --color-navy:           #0B1120;
  --color-navy-mid:       #111827;
  --color-navy-surface:   #1a2540;
  --color-navy-border:    #243050;
  --color-white:          #ffffff;
  --color-offwhite:       #f8fafc;
  --color-text:           #e2e8f0;
  --color-text-muted:     #94a3b8;
  --color-accent-violet:  #6366F1;
  --color-accent-green:   #22C55E;
  --color-accent-amber:   #F59E0B;
  --color-accent-pink:    #EC4899;
  --color-accent-sky:     #0EA5E9;

  /* Typography */
  --font-sans:   'Inter', system-ui, -apple-system, sans-serif;
  --text-xs:     0.75rem;
  --text-sm:     0.875rem;
  --text-base:   1rem;
  --text-lg:     1.125rem;
  --text-xl:     1.25rem;
  --text-2xl:    1.5rem;
  --text-3xl:    1.875rem;
  --text-4xl:    2.25rem;
  --text-5xl:    3rem;
  --text-6xl:    3.75rem;
  --fw-normal:   400;
  --fw-medium:   500;
  --fw-semibold: 600;
  --fw-bold:     700;
  --fw-extrabold:800;
  --leading-tight:  1.2;
  --leading-snug:   1.375;
  --leading-normal: 1.5;
  --leading-relaxed:1.65;

  /* Spacing (8-pt grid) */
  --space-1:  0.25rem;   /*  4px */
  --space-2:  0.5rem;    /*  8px */
  --space-3:  0.75rem;   /* 12px */
  --space-4:  1rem;      /* 16px */
  --space-5:  1.25rem;   /* 20px */
  --space-6:  1.5rem;    /* 24px */
  --space-8:  2rem;      /* 32px */
  --space-10: 2.5rem;    /* 40px */
  --space-12: 3rem;      /* 48px */
  --space-16: 4rem;      /* 64px */
  --space-20: 5rem;      /* 80px */
  --space-24: 6rem;      /* 96px */

  /* Layout */
  --container-max: 1200px;
  --container-px:  var(--space-6);

  /* Radii */
  --radius-sm:   0.375rem;
  --radius-md:   0.625rem;
  --radius-lg:   1rem;
  --radius-xl:   1.5rem;
  --radius-full: 9999px;

  /* Shadows */
  --shadow-sm:  0 1px 3px rgba(0,0,0,.35), 0 1px 2px rgba(0,0,0,.25);
  --shadow-md:  0 4px 12px rgba(0,0,0,.4),  0 2px 6px rgba(0,0,0,.25);
  --shadow-lg:  0 10px 30px rgba(0,0,0,.5), 0 4px 12px rgba(0,0,0,.3);
  --shadow-glow-primary: 0 0 20px rgba(255,107,53,.35);
  --shadow-glow-violet:  0 0 20px rgba(99,102,241,.3);

  /* Gradients */
  --gradient-primary:  linear-gradient(135deg, #FF6B35 0%, #e84393 100%);
  --gradient-hero:     linear-gradient(160deg, #0B1120 0%, #111827 60%, #1a2540 100%);
  --gradient-card:     linear-gradient(145deg, #1a2540 0%, #111827 100%);
  --gradient-cta:      linear-gradient(135deg, #FF6B35 0%, #6366F1 100%);
  --gradient-text:     linear-gradient(90deg, #FF6B35, #F59E0B, #ec4899);

  /* Transitions */
  --ease-fast:   150ms cubic-bezier(.4,0,.2,1);
  --ease-normal: 250ms cubic-bezier(.4,0,.2,1);
  --ease-slow:   400ms cubic-bezier(.4,0,.2,1);
}

/* ============================================================
   RESET & BASE
   ============================================================ */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html {
  scroll-behavior: smooth;
  -webkit-text-size-adjust: 100%;
}

body {
  font-family: var(--font-sans);
  font-size: var(--text-base);
  font-weight: var(--fw-normal);
  line-height: var(--leading-relaxed);
  color: var(--color-text);
  background-color: var(--color-navy);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
}

img, svg { display: block; max-width: 100%; }
a { color: inherit; text-decoration: none; }
ul, ol { list-style: none; }
button { cursor: pointer; border: none; background: none; font: inherit; }

/* ============================================================
   UTILITIES
   ============================================================ */
.sr-only {
  position: absolute;
  width: 1px; height: 1px;
  padding: 0; margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  white-space: nowrap;
  border-width: 0;
}

.container {
  width: 100%;
  max-width: var(--container-max);
  margin-inline: auto;
  padding-inline: var(--container-px);
}

.gradient-text {
  background: var(--gradient-text);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

/* ============================================================
   BUTTONS
   ============================================================ */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-2);
  padding: var(--space-3) var(--space-6);
  border-radius: var(--radius-full);
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  line-height: 1;
  transition:
    background-color var(--ease-fast),
    color var(--ease-fast),
    transform var(--ease-fast),
    box-shadow var(--ease-fast),
    border-color var(--ease-fast);
  white-space: nowrap;
  border: 2px solid transparent;
}

.btn:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 3px;
}

.btn:active { transform: scale(.97); }

.btn-primary {
  background: var(--color-primary);
  color: var(--color-white);
  box-shadow: var(--shadow-sm), var(--shadow-glow-primary);
}
.btn-primary:hover {
  background: var(--color-primary-dark);
  box-shadow: var(--shadow-md), var(--shadow-glow-primary);
  transform: translateY(-1px);
}

.btn-ghost {
  background: transparent;
  color: var(--color-text);
  border-color: transparent;
}
.btn-ghost:hover {
  background: rgba(255,255,255,.08);
  color: var(--color-white);
}

.btn-outline {
  background: transparent;
  color: var(--color-white);
  border-color: rgba(255,255,255,.3);
}
.btn-outline:hover {
  background: rgba(255,255,255,.08);
  border-color: rgba(255,255,255,.6);
  transform: translateY(-1px);
}

.btn-white {
  background: var(--color-white);
  color: var(--color-navy);
  font-weight: var(--fw-bold);
}
.btn-white:hover {
  background: var(--color-offwhite);
  box-shadow: var(--shadow-md);
  transform: translateY(-2px);
}

.btn-lg {
  padding: var(--space-4) var(--space-8);
  font-size: var(--text-base);
}

/* ============================================================
   HEADER & NAV
   ============================================================ */
.header {
  position: sticky;
  top: 0;
  z-index: 100;
  background: rgba(11,17,32,.85);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border-bottom: 1px solid var(--color-navy-border);
  box-shadow: 0 1px 0 rgba(255,255,255,.04);
}

.nav {
  display: flex;
  align-items: center;
  gap: var(--space-8);
  height: 68px;
}

.logo {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  flex-shrink: 0;
}

.logo-text {
  font-size: var(--text-xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.02em;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  margin-left: auto;
}

.nav-links a {
  padding: var(--space-2) var(--space-4);
  border-radius: var(--radius-md);
  font-size: var(--text-sm);
  font-weight: var(--fw-medium);
  color: var(--color-text-muted);
  transition: color var(--ease-fast), background-color var(--ease-fast);
}
.nav-links a:hover {
  color: var(--color-white);
  background: rgba(255,255,255,.06);
}

.nav-actions {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  flex-shrink: 0;
}

.hamburger {
  display: none;
  flex-direction: column;
  gap: 5px;
  padding: var(--space-2);
  margin-left: auto;
  border-radius: var(--radius-sm);
}
.hamburger span {
  display: block;
  width: 22px;
  height: 2px;
  background: var(--color-text);
  border-radius: var(--radius-full);
  transition: transform var(--ease-normal), opacity var(--ease-normal);
}
.hamburger[aria-expanded="true"] span:nth-child(1) { transform: translateY(7px) rotate(45deg); }
.hamburger[aria-expanded="true"] span:nth-child(2) { opacity: 0; }
.hamburger[aria-expanded="true"] span:nth-child(3) { transform: translateY(-7px) rotate(-45deg); }

.mobile-menu {
  border-top: 1px solid var(--color-navy-border);
  background: var(--color-navy-mid);
  padding: var(--space-4) var(--container-px);
}
.mobile-menu ul { display: flex; flex-direction: column; gap: var(--space-1); }
.mobile-menu a {
  display: block;
  padding: var(--space-3) var(--space-4);
  border-radius: var(--radius-md);
  color: var(--color-text-muted);
  font-weight: var(--fw-medium);
  transition: color var(--ease-fast), background var(--ease-fast);
}
.mobile-menu a:hover { color: var(--color-white); background: rgba(255,255,255,.06); }
.mobile-menu .btn-primary { margin-top: var(--space-3); width: 100%; border-radius: var(--radius-full); }

/* ============================================================
   HERO
   ============================================================ */
.hero {
  background: var(--gradient-hero);
  padding-block: var(--space-24) var(--space-16);
  overflow: hidden;
  position: relative;
}

.hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(ellipse 60% 50% at 70% 40%, rgba(99,102,241,.12) 0%, transparent 60%),
    radial-gradient(ellipse 40% 35% at 20% 60%, rgba(255,107,53,.08) 0%, transparent 55%);
  pointer-events: none;
}

.hero-inner {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-16);
  align-items: center;
  position: relative;
}

.hero-content { display: flex; flex-direction: column; gap: var(--space-6); }

.hero-eyebrow {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  color: var(--color-primary);
  letter-spacing: .06em;
  text-transform: uppercase;
}
.hero-eyebrow::before {
  content: '';
  display: block;
  width: 24px;
  height: 2px;
  background: var(--color-primary);
  border-radius: var(--radius-full);
}

.hero-heading {
  font-size: var(--text-5xl);
  font-weight: var(--fw-extrabold);
  line-height: var(--leading-tight);
  letter-spacing: -.03em;
  color: var(--color-white);
}

.hero-subtext {
  font-size: var(--text-lg);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
  max-width: 48ch;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-4);
  align-items: center;
}

.hero-note {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  color: var(--color-text-muted);
}

/* Hero visual cards */
.hero-image {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 380px;
}

.hero-card {
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-lg);
  border: 1px solid var(--color-navy-border);
}

.hero-card--main {
  background: var(--color-navy-surface);
  padding: var(--space-4);
  width: 100%;
  max-width: 420px;
}

.hero-card--badge {
  position: absolute;
  display: flex;
  align-items: center;
  gap: var(--space-3);
  background: var(--color-navy-mid);
  padding: var(--space-3) var(--space-4);
  border-radius: var(--radius-xl);
  font-size: var(--text-sm);
  min-width: 200px;
}
.hero-card--badge strong { display: block; color: var(--color-white); font-weight: var(--fw-semibold); }
.hero-card--badge span   { color: var(--color-text-muted); font-size: var(--text-xs); }

.hero-card--offer  { bottom: 24px; left: -20px; }
.hero-card--mentor { top: 20px; right: -20px; }

.badge-icon { font-size: 1.5rem; }

/* Code window */
.code-window { border-radius: var(--radius-lg); overflow: hidden; background: #0d1117; }

.code-window-bar {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-3) var(--space-4);
  background: #161b22;
  border-bottom: 1px solid rgba(255,255,255,.07);
}

.dot {
  width: 12px; height: 12px;
  border-radius: var(--radius-full);
  flex-shrink: 0;
}
.dot--red    { background: #ff5f57; }
.dot--yellow { background: #febc2e; }
.dot--green  { background: #28c840; }

.code-snippet {
  padding: var(--space-4) var(--space-5);
  overflow-x: auto;
  font-size: var(--text-xs);
  line-height: 1.75;
  font-family: 'Fira Code', 'Cascadia Code', 'JetBrains Mono', monospace;
  color: #c9d1d9;
}

.code-snippet .kw  { color: #ff7b72; }
.code-snippet .fn  { color: #d2a8ff; }
.code-snippet .num { color: #79c0ff; }

/* ============================================================
   STATS
   ============================================================ */
.stats {
  background: var(--color-navy-mid);
  padding-block: var(--space-16);
  border-block: 1px solid var(--color-navy-border);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--space-6);
}

.stat-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: var(--space-2);
  padding: var(--space-6);
  border-radius: var(--radius-lg);
  background: var(--gradient-card);
  border: 1px solid var(--color-navy-border);
  transition: transform var(--ease-normal), box-shadow var(--ease-normal);
}
.stat-item:hover {
  transform: translateY(-3px);
  box-shadow: var(--shadow-md);
}

.stat-number {
  font-size: var(--text-4xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.03em;
  line-height: 1;
}

.stat-suffix {
  font-size: var(--text-2xl);
  font-weight: var(--fw-bold);
  color: var(--color-primary);
  line-height: 1;
  margin-top: -.25em;
  align-self: flex-start;
}

.stat-label {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  font-weight: var(--fw-medium);
}

/* ============================================================
   SECTION COMMONS
   ============================================================ */
.section-header {
  text-align: center;
  max-width: 640px;
  margin-inline: auto;
  margin-bottom: var(--space-16);
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.section-eyebrow {
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  color: var(--color-primary);
  letter-spacing: .08em;
  text-transform: uppercase;
}

.section-title {
  font-size: var(--text-4xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.03em;
  line-height: var(--leading-tight);
}

.section-subtitle {
  font-size: var(--text-lg);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
}

/* ============================================================
   FEATURES
   ============================================================ */
.features {
  padding-block: var(--space-24);
  background: var(--color-navy);
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-6);
}

.feature-card {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  padding: var(--space-8);
  border-radius: var(--radius-xl);
  background: var(--gradient-card);
  border: 1px solid var(--color-navy-border);
  box-shadow: var(--shadow-sm);
  transition: transform var(--ease-normal), box-shadow var(--ease-normal), border-color var(--ease-normal);
}
.feature-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-md);
  border-color: rgba(255,107,53,.25);
}

.feature-icon {
  width: 52px; height: 52px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-lg);
  background: rgba(255,255,255,.05);
  flex-shrink: 0;
}

.feature-card h3 {
  font-size: var(--text-lg);
  font-weight: var(--fw-bold);
  color: var(--color-white);
  letter-spacing: -.01em;
}

.feature-card p {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
}

/* ============================================================
   TESTIMONIALS
   ============================================================ */
.testimonials {
  padding-block: var(--space-24);
  background: var(--color-navy-mid);
}

.testimonials-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-6);
}

.testimonial-card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: var(--space-6);
  padding: var(--space-8);
  border-radius: var(--radius-xl);
  background: var(--gradient-card);
  border: 1px solid var(--color-navy-border);
  box-shadow: var(--shadow-sm);
  transition: transform var(--ease-normal), box-shadow var(--ease-normal);
}
.testimonial-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-lg);
}

.testimonial-card blockquote p {
  font-size: var(--text-base);
  color: var(--color-text);
  line-height: var(--leading-relaxed);
  font-style: italic;
  position: relative;
}
.testimonial-card blockquote p::before {
  content: '“';
  font-size: 4rem;
  line-height: 0;
  vertical-align: -.5em;
  color: var(--color-primary);
  opacity: .4;
  margin-right: var(--space-1);
}

.testimonial-author {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding-top: var(--space-4);
  border-top: 1px solid var(--color-navy-border);
}
.testimonial-author strong { display: block; color: var(--color-white); font-size: var(--text-sm); font-weight: var(--fw-semibold); }
.testimonial-author span   { color: var(--color-text-muted); font-size: var(--text-xs); }
.testimonial-author > div  { flex: 1; }

.salary-badge {
  font-size: var(--text-xs);
  font-weight: var(--fw-bold);
  color: var(--color-accent-green);
  background: rgba(34,197,94,.1);
  border: 1px solid rgba(34,197,94,.25);
  border-radius: var(--radius-full);
  padding: var(--space-1) var(--space-3);
  flex-shrink: 0;
}

.avatar {
  border-radius: var(--radius-full);
  object-fit: cover;
  flex-shrink: 0;
  border: 2px solid var(--color-navy-border);
}

/* ============================================================
   CTA BANNER
   ============================================================ */
.cta-banner {
  background: var(--gradient-cta);
  padding-block: var(--space-20);
  position: relative;
  overflow: hidden;
}
.cta-banner::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(circle at 20% 50%, rgba(255,255,255,.08) 0%, transparent 50%),
    radial-gradient(circle at 80% 50%, rgba(0,0,0,.1) 0%, transparent 50%);
  pointer-events: none;
}

.cta-inner {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-8);
  flex-wrap: wrap;
}

.cta-inner h2 {
  font-size: var(--text-3xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.02em;
  line-height: var(--leading-tight);
}

.cta-inner p {
  font-size: var(--text-lg);
  color: rgba(255,255,255,.8);
  margin-top: var(--space-2);
}

/* ============================================================
   FOOTER
   ============================================================ */
.footer {
  background: var(--color-navy-mid);
  border-top: 1px solid var(--color-navy-border);
}

.footer-inner {
  display: grid;
  grid-template-columns: 1.5fr 1fr;
  gap: var(--space-16);
  padding-block: var(--space-16);
}

.footer-brand {
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
}
.footer-brand p {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
  max-width: 36ch;
}

.social-links {
  display: flex;
  gap: var(--space-3);
}
.social-links a {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px; height: 40px;
  border-radius: var(--radius-md);
  color: var(--color-text-muted);
  background: rgba(255,255,255,.05);
  border: 1px solid var(--color-navy-border);
  transition: color var(--ease-fast), background var(--ease-fast), transform var(--ease-fast);
}
.social-links a:hover {
  color: var(--color-white);
  background: rgba(255,107,53,.12);
  border-color: rgba(255,107,53,.3);
  transform: translateY(-2px);
}

.footer-links {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-8);
}

.footer-col h3 {
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  color: var(--color-white);
  letter-spacing: .04em;
  text-transform: uppercase;
  margin-bottom: var(--space-5);
}
.footer-col ul { display: flex; flex-direction: column; gap: var(--space-3); }
.footer-col a {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  transition: color var(--ease-fast);
}
.footer-col a:hover { color: var(--color-white); }

.footer-bottom {
  border-top: 1px solid var(--color-navy-border);
  padding-block: var(--space-6);
}
.footer-bottom .container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-4);
}
.footer-bottom p { font-size: var(--text-sm); color: var(--color-text-muted); }

/* ============================================================
   RESPONSIVE — Tablet (≤ 900px)
   ============================================================ */
@media (max-width: 900px) {
  :root { --container-px: var(--space-5); }

  .hero-inner { grid-template-columns: 1fr; gap: var(--space-12); }
  .hero-heading { font-size: var(--text-4xl); }
  .hero-image { display: none; }

  .stats-grid { grid-template-columns: repeat(2, 1fr); }

  .features-grid { grid-template-columns: repeat(2, 1fr); }

  .testimonials-grid { grid-template-columns: 1fr; }

  .cta-inner { flex-direction: column; text-align: center; }

  .footer-inner { grid-template-columns: 1fr; gap: var(--space-10); }
  .footer-links { grid-template-columns: repeat(3, 1fr); }

  .nav-links, .nav-actions { display: none; }
  .hamburger { display: flex; }
}

/* ============================================================
   RESPONSIVE — Mobile (≤ 600px)
   ============================================================ */
@media (max-width: 600px) {
  :root { --container-px: var(--space-4); }

  .hero { padding-block: var(--space-16) var(--space-12); }
  .hero-heading { font-size: var(--text-3xl); }
  .hero-actions { flex-direction: column; align-items: stretch; }
  .hero-actions .btn { width: 100%; justify-content: center; }

  .section-title { font-size: var(--text-3xl); }

  .stats-grid { grid-template-columns: repeat(2, 1fr); gap: var(--space-4); }
  .stat-number { font-size: var(--text-3xl); }

  .features-grid { grid-template-columns: 1fr; }

  .cta-inner h2 { font-size: var(--text-2xl); }

  .footer-links { grid-template-columns: repeat(2, 1fr); gap: var(--space-6); }
  .footer-bottom .container { flex-direction: column; text-align: center; }
}

/* ============================================================
   SCROLLBAR STYLING
   ============================================================ */
::-webkit-scrollbar { width: 8px; height: 8px; }
::-webkit-scrollbar-track { background: var(--color-navy-mid); }
::-webkit-scrollbar-thumb {
  background: var(--color-navy-border);
  border-radius: var(--radius-full);
}
::-webkit-scrollbar-thumb:hover { background: rgba(255,107,53,.4); }

/* ============================================================
   SELECTION
   ============================================================ */
::selection { background: rgba(255,107,53,.3); color: var(--color-white); }

${extraRules}`;
}

export const generateCSSTool: Tool = {
  name: "generateCSS",
  description:
    "Generate a complete, premium CSS stylesheet (dark-blue/white theme, CSS variables, Flexbox + Grid, spacing system, responsive design, hover effects, shadows, gradients) matching the Scaler Academy landing page and write it to the output directory.",
  inputSchema: {
    filename: {
      type: "string",
      description: "Output filename, e.g. styles.css",
      required: true,
    },
    rules: {
      type: "string",
      description: "Optional extra CSS rules appended after the generated stylesheet.",
    },
  },

  async execute(raw: ToolInput): Promise<ToolResult> {
    if (!isGenerateCSSInput(raw)) {
      return { success: false, error: "Missing required field: filename" };
    }

    const input = raw as GenerateCSSInput;
    const extraRules = typeof input.rules === "string" && input.rules ? input.rules : "";
    const css = buildPremiumCSS(extraRules);

    return writeFileTool.execute({
      filePath: input.filename,
      content: css,
    });
  },
};
