import { type Tool, type ToolInput, type ToolResult } from "./registry.js";
import { writeFileTool } from "./writeFile.js";

interface GenerateCSSInput {
  filename: string;
  rules?: string;
}

function isGenerateCSSInput(input: unknown): input is GenerateCSSInput {
  if (typeof input !== "object" || input === null) return false;
  const i = input as Record<string, unknown>;
  return typeof i["filename"] === "string";
}

function buildPremiumCSS(extraRules: string): string {
  return `/* Generated by AI Agent CLI — ${new Date().toISOString()} */

/* ============================================================
   CSS VARIABLES — Design tokens
   ============================================================ */
:root {
  /* ── Required brand tokens ── */
  --primary:    #ff7a18;
  --secondary:  #1a2a6c;
  --bg-dark:    #0b1220;
  --text-light: #ffffff;

  /* ── Extended color palette ── */
  --color-primary:        var(--primary);
  --color-primary-dark:   #e56a10;
  --color-primary-light:  #ff9844;
  --color-navy:           var(--bg-dark);
  --color-navy-mid:       #0f1a2e;
  --color-navy-surface:   #162038;
  --color-navy-border:    #1e2d4a;
  --color-white:          var(--text-light);
  --color-offwhite:       #f0f4ff;
  --color-text:           #dde6f0;
  --color-text-muted:     #7a90b0;
  --color-accent-violet:  #6366F1;
  --color-accent-green:   #22C55E;
  --color-accent-amber:   #F59E0B;
  --color-accent-pink:    #EC4899;
  --color-accent-sky:     #0EA5E9;

  /* ── Typography ── */
  --font-sans:   'Inter', system-ui, -apple-system, sans-serif;
  --font-mono:   'Fira Code', 'Cascadia Code', 'JetBrains Mono', monospace;
  --text-xs:     0.75rem;
  --text-sm:     0.875rem;
  --text-base:   1rem;
  --text-lg:     1.125rem;
  --text-xl:     1.25rem;
  --text-2xl:    1.5rem;
  --text-3xl:    1.875rem;
  --text-4xl:    2.25rem;
  --text-5xl:    3.25rem;
  --text-6xl:    4rem;
  --fw-normal:   400;
  --fw-medium:   500;
  --fw-semibold: 600;
  --fw-bold:     700;
  --fw-extrabold:800;
  --leading-tight:  1.15;
  --leading-snug:   1.35;
  --leading-normal: 1.5;
  --leading-relaxed:1.7;

  /* ── Spacing (8-pt grid) ── */
  --space-1:  0.25rem;
  --space-2:  0.5rem;
  --space-3:  0.75rem;
  --space-4:  1rem;
  --space-5:  1.25rem;
  --space-6:  1.5rem;
  --space-8:  2rem;
  --space-10: 2.5rem;
  --space-12: 3rem;
  --space-16: 4rem;
  --space-20: 5rem;   /* 80px section padding */
  --space-24: 6rem;

  /* ── Layout ── */
  --container-max: 1200px;
  --container-px:  var(--space-6);

  /* ── Radii ── */
  --radius-sm:   0.375rem;
  --radius-md:   0.625rem;
  --radius-lg:   1rem;
  --radius-xl:   1.5rem;
  --radius-2xl:  2rem;
  --radius-full: 9999px;

  /* ── Shadows ── */
  --shadow-sm:  0 1px 3px rgba(0,0,0,.4), 0 1px 2px rgba(0,0,0,.3);
  --shadow-md:  0 4px 16px rgba(0,0,0,.5), 0 2px 6px rgba(0,0,0,.3);
  --shadow-lg:  0 12px 40px rgba(0,0,0,.6), 0 4px 12px rgba(0,0,0,.4);
  --shadow-glow-primary: 0 0 32px rgba(255,122,24,.45), 0 0 64px rgba(255,122,24,.15);
  --shadow-glow-blue:    0 0 40px rgba(26,42,108,.6),   0 0 80px rgba(99,102,241,.2);
  --shadow-glow-card:    0 0 24px rgba(99,102,241,.25), 0 0 48px rgba(26,42,108,.4);

  /* ── Gradients ── */
  --gradient-primary:  linear-gradient(135deg, #ff7a18 0%, #ec4899 100%);
  --gradient-hero:     linear-gradient(150deg, #0b1220 0%, #0f1a2e 45%, #1a2a6c 100%);
  --gradient-hero-alt: linear-gradient(135deg, #0b1220 0%, #111d3a 50%, #1a2a6c 100%);
  --gradient-card:     linear-gradient(145deg, #162038 0%, #0f1a2e 100%);
  --gradient-cta:      linear-gradient(135deg, #ff7a18 0%, #1a2a6c 100%);
  --gradient-text:     linear-gradient(95deg, #ff7a18 0%, #f59e0b 40%, #ec4899 100%);
  --gradient-border:   linear-gradient(135deg, rgba(255,122,24,.4), rgba(99,102,241,.4));

  /* ── Transitions ── */
  --ease-fast:   150ms cubic-bezier(.4,0,.2,1);
  --ease-normal: 260ms cubic-bezier(.4,0,.2,1);
  --ease-slow:   420ms cubic-bezier(.4,0,.2,1);
}

/* ============================================================
   RESET & BASE
   ============================================================ */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html {
  scroll-behavior: smooth;
  -webkit-text-size-adjust: 100%;
}

body {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  font-size: var(--text-base);
  font-weight: var(--fw-normal);
  font-optical-sizing: auto;
  line-height: var(--leading-relaxed);
  color: var(--color-text);
  background-color: var(--bg-dark);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
}

img, svg { display: block; max-width: 100%; }
a { color: inherit; text-decoration: none; }
ul, ol { list-style: none; }
button { cursor: pointer; border: none; background: none; font: inherit; }

/* ============================================================
   UTILITIES
   ============================================================ */
.sr-only {
  position: absolute;
  width: 1px; height: 1px;
  padding: 0; margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  white-space: nowrap;
  border-width: 0;
}

.container {
  width: 100%;
  max-width: var(--container-max);
  margin-inline: auto;
  padding-inline: var(--container-px);
}

.gradient-text {
  background: linear-gradient(95deg, #ff7a18 0%, #f59e0b 45%, #ec4899 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  color: transparent; /* standard fallback for non-webkit */
}

/* ============================================================
   BUTTONS
   ============================================================ */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-2);
  padding: var(--space-3) var(--space-6);
  border-radius: var(--radius-full);
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  line-height: 1;
  transition:
    background-color var(--ease-fast),
    color var(--ease-fast),
    transform var(--ease-fast),
    box-shadow var(--ease-fast),
    border-color var(--ease-fast);
  white-space: nowrap;
  border: 2px solid transparent;
}

.btn:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 3px;
}

.btn:active { transform: scale(.97); }

.btn-primary {
  background: var(--primary);
  color: var(--text-light);
  box-shadow: var(--shadow-sm), var(--shadow-glow-primary);
}
.btn-primary:hover {
  background: var(--color-primary-dark);
  box-shadow: var(--shadow-md), var(--shadow-glow-primary);
  transform: translateY(-2px);
}

.btn-ghost {
  background: transparent;
  color: var(--color-text);
  border-color: transparent;
}
.btn-ghost:hover {
  background: rgba(255,255,255,.08);
  color: var(--color-white);
}

.btn-outline {
  background: transparent;
  color: var(--color-white);
  border-color: rgba(255,255,255,.3);
}
.btn-outline:hover {
  background: rgba(255,255,255,.08);
  border-color: rgba(255,255,255,.6);
  transform: translateY(-1px);
}

.btn-white {
  background: var(--color-white);
  color: var(--color-navy);
  font-weight: var(--fw-bold);
}
.btn-white:hover {
  background: var(--color-offwhite);
  box-shadow: var(--shadow-md);
  transform: translateY(-2px);
}

.btn-lg {
  padding: var(--space-4) var(--space-8);
  font-size: var(--text-base);
}

/* ============================================================
   HEADER & NAV
   ============================================================ */
.header {
  position: sticky;
  top: 0;
  z-index: 100;
  background: rgba(11,18,32,.9);
  backdrop-filter: blur(20px) saturate(180%);
  -webkit-backdrop-filter: blur(20px) saturate(180%);
  border-bottom: 1px solid rgba(30,45,74,.8);
  box-shadow: 0 1px 0 rgba(255,255,255,.03), 0 4px 24px rgba(0,0,0,.3);
}

.nav {
  display: flex;
  align-items: center;
  gap: var(--space-8);
  height: 68px;
}

.logo {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  flex-shrink: 0;
}

.logo-text {
  font-size: var(--text-xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.02em;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  margin-left: auto;
}

.nav-links a {
  padding: var(--space-2) var(--space-4);
  border-radius: var(--radius-md);
  font-size: var(--text-sm);
  font-weight: var(--fw-medium);
  color: var(--color-text-muted);
  transition: color var(--ease-fast), background-color var(--ease-fast);
}
.nav-links a:hover {
  color: var(--color-white);
  background: rgba(255,255,255,.06);
}

.nav-actions {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  flex-shrink: 0;
}

.hamburger {
  display: none;
  flex-direction: column;
  gap: 5px;
  padding: var(--space-2);
  margin-left: auto;
  border-radius: var(--radius-sm);
}
.hamburger span {
  display: block;
  width: 22px;
  height: 2px;
  background: var(--color-text);
  border-radius: var(--radius-full);
  transition: transform var(--ease-normal), opacity var(--ease-normal);
}
.hamburger[aria-expanded="true"] span:nth-child(1) { transform: translateY(7px) rotate(45deg); }
.hamburger[aria-expanded="true"] span:nth-child(2) { opacity: 0; }
.hamburger[aria-expanded="true"] span:nth-child(3) { transform: translateY(-7px) rotate(-45deg); }

.mobile-menu {
  border-top: 1px solid var(--color-navy-border);
  background: var(--color-navy-mid);
  padding: var(--space-4) var(--container-px);
}
.mobile-menu ul { display: flex; flex-direction: column; gap: var(--space-1); }
.mobile-menu a {
  display: block;
  padding: var(--space-3) var(--space-4);
  border-radius: var(--radius-md);
  color: var(--color-text-muted);
  font-weight: var(--fw-medium);
  transition: color var(--ease-fast), background var(--ease-fast);
}
.mobile-menu a:hover { color: var(--color-white); background: rgba(255,255,255,.06); }
.mobile-menu .btn-primary { margin-top: var(--space-3); width: 100%; border-radius: var(--radius-full); }

/* ============================================================
   HERO
   ============================================================ */
.hero {
  background: var(--gradient-hero);
  padding-block: var(--space-24) var(--space-20);
  overflow: hidden;
  position: relative;
  min-height: 90vh;
  display: flex;
  align-items: center;
}

/* Dot-grid texture overlay */
.hero::after {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(circle, rgba(255,255,255,.04) 1px, transparent 1px);
  background-size: 32px 32px;
  pointer-events: none;
}

.hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(ellipse 70% 60% at 75% 50%, rgba(99,102,241,.18) 0%, transparent 60%),
    radial-gradient(ellipse 50% 45% at 15% 70%, rgba(255,122,24,.12) 0%, transparent 55%),
    radial-gradient(ellipse 45% 50% at 85% 10%, rgba(26,42,108,.5) 0%, transparent 65%);
  pointer-events: none;
  z-index: 0;
}

.hero .container { position: relative; z-index: 1; width: 100%; }

.hero-inner {
  display: grid;
  grid-template-columns: 55% 45%;
  gap: var(--space-12);
  align-items: center;
}

.hero-content { display: flex; flex-direction: column; gap: var(--space-6); }

.hero-eyebrow {
  display: inline-flex;
  align-items: center;
  gap: var(--space-3);
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  color: var(--primary);
  letter-spacing: .08em;
  text-transform: uppercase;
  width: fit-content;
  background: rgba(255,122,24,.08);
  border: 1px solid rgba(255,122,24,.2);
  padding: var(--space-1) var(--space-4) var(--space-1) var(--space-2);
  border-radius: var(--radius-full);
}
.hero-eyebrow::before {
  content: '';
  display: block;
  width: 8px; height: 8px;
  background: var(--primary);
  border-radius: var(--radius-full);
  box-shadow: 0 0 6px var(--primary);
  animation: pulse-dot 2s ease-in-out infinite;
}

@keyframes pulse-dot {
  0%, 100% { opacity: 1; box-shadow: 0 0 6px var(--primary); }
  50%       { opacity: .6; box-shadow: 0 0 12px var(--primary); }
}

.hero-heading {
  font-size: clamp(2.75rem, 5vw, var(--text-6xl));
  font-weight: var(--fw-extrabold);
  line-height: var(--leading-tight);
  letter-spacing: -.04em;
  color: var(--text-light);
}

.hero-subtext {
  font-size: var(--text-lg);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
  max-width: 46ch;
  opacity: .85;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-4);
  align-items: center;
  padding-top: var(--space-2);
}

.hero-note {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  opacity: .75;
}

/* ── Hero visual ── */
.hero-image {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 420px;
  padding: var(--space-8);
}

/* Ambient glow behind the card */
.hero-image::before {
  content: '';
  position: absolute;
  inset: 10% 5%;
  background: radial-gradient(ellipse at center, rgba(99,102,241,.3) 0%, rgba(26,42,108,.2) 50%, transparent 75%);
  border-radius: 50%;
  filter: blur(32px);
  z-index: 0;
}

.hero-card {
  border-radius: var(--radius-2xl);
  box-shadow: var(--shadow-lg);
  border: 1px solid var(--color-navy-border);
  position: relative;
  z-index: 1;
}

.hero-card--main {
  background: linear-gradient(160deg, #1a2848 0%, #0f1a2e 100%);
  padding: var(--space-3);
  width: 100%;
  max-width: 440px;
  border: 1px solid rgba(99,102,241,.25);
  box-shadow:
    var(--shadow-lg),
    var(--shadow-glow-card),
    inset 0 1px 0 rgba(255,255,255,.06);
}

.hero-card--badge {
  position: absolute;
  display: flex;
  align-items: center;
  gap: var(--space-3);
  background: rgba(15,26,46,.95);
  padding: var(--space-3) var(--space-4);
  border-radius: var(--radius-xl);
  font-size: var(--text-sm);
  min-width: 210px;
  backdrop-filter: blur(12px);
  border: 1px solid var(--color-navy-border);
  box-shadow: var(--shadow-md), 0 0 16px rgba(0,0,0,.4);
  z-index: 2;
  animation: float 4s ease-in-out infinite;
}
.hero-card--badge strong { display: block; color: var(--text-light); font-weight: var(--fw-semibold); font-size: var(--text-sm); }
.hero-card--badge span   { color: var(--color-text-muted); font-size: var(--text-xs); }

.hero-card--offer  { bottom: 20px; left: -24px; animation-delay: 0s; }
.hero-card--mentor { top: 16px; right: -24px; animation-delay: 2s; }

@keyframes float {
  0%, 100% { transform: translateY(0); }
  50%       { transform: translateY(-6px); }
}

.badge-icon { font-size: 1.4rem; flex-shrink: 0; }

/* ── Code window ── */
.code-window {
  border-radius: var(--radius-lg);
  overflow: hidden;
  background: #080e1a;
  border: 1px solid rgba(255,255,255,.06);
}

.code-window-bar {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-3) var(--space-4);
  background: #0d1525;
  border-bottom: 1px solid rgba(255,255,255,.06);
}

.code-window-title {
  margin-left: auto;
  font-size: 11px;
  color: rgba(255,255,255,.25);
  font-family: var(--font-mono);
  letter-spacing: .04em;
}

.dot {
  width: 12px; height: 12px;
  border-radius: var(--radius-full);
  flex-shrink: 0;
}
.dot--red    { background: #ff5f57; box-shadow: 0 0 4px rgba(255,95,87,.5); }
.dot--yellow { background: #febc2e; box-shadow: 0 0 4px rgba(254,188,46,.5); }
.dot--green  { background: #28c840; box-shadow: 0 0 4px rgba(40,200,64,.5); }

.code-snippet {
  padding: var(--space-5) var(--space-5);
  overflow-x: auto;
  font-size: 0.8rem;
  line-height: 1.8;
  font-family: var(--font-mono);
  color: #a8b8d0;
}

.code-snippet .kw   { color: #f97583; }
.code-snippet .fn   { color: #b392f0; }
.code-snippet .num  { color: #79c0ff; }
.code-snippet .str  { color: #9ecbff; }
.code-snippet .cmt  { color: #444d5e; font-style: italic; }
.code-snippet .op   { color: #f97583; }

/* ============================================================
   STATS
   ============================================================ */
.stats {
  background: var(--color-navy-mid);
  padding-block: var(--space-20);
  border-block: 1px solid var(--color-navy-border);
  position: relative;
  overflow: hidden;
}
.stats::before {
  content: '';
  position: absolute;
  inset: 0;
  background: radial-gradient(ellipse 80% 60% at 50% 50%, rgba(26,42,108,.15) 0%, transparent 70%);
  pointer-events: none;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--space-6);
  position: relative;
}

.stat-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: var(--space-2);
  padding: var(--space-8) var(--space-6);
  border-radius: var(--radius-xl);
  background: var(--gradient-card);
  border: 1px solid var(--color-navy-border);
  transition: transform var(--ease-normal), box-shadow var(--ease-normal), border-color var(--ease-normal);
  position: relative;
  overflow: hidden;
}
.stat-item::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 2px;
  background: var(--gradient-primary);
  opacity: 0;
  transition: opacity var(--ease-normal);
}
.stat-item:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-md), 0 0 20px rgba(26,42,108,.3);
  border-color: rgba(99,102,241,.3);
}
.stat-item:hover::before { opacity: 1; }

.stat-number {
  font-size: var(--text-5xl);
  font-weight: var(--fw-extrabold);
  color: var(--text-light);
  letter-spacing: -.04em;
  line-height: 1;
}

.stat-suffix {
  font-size: var(--text-2xl);
  font-weight: var(--fw-bold);
  color: var(--primary);
  line-height: 1;
  margin-top: -.3em;
  align-self: flex-start;
}

.stat-label {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  font-weight: var(--fw-medium);
  margin-top: var(--space-1);
}

/* ============================================================
   SECTION COMMONS
   ============================================================ */
.section-header {
  text-align: center;
  max-width: 640px;
  margin-inline: auto;
  margin-bottom: var(--space-16);
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.section-eyebrow {
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  color: var(--color-primary);
  letter-spacing: .08em;
  text-transform: uppercase;
}

.section-title {
  font-size: var(--text-4xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.03em;
  line-height: var(--leading-tight);
}

.section-subtitle {
  font-size: var(--text-lg);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
}

/* ============================================================
   FEATURES
   ============================================================ */
.features {
  padding-block: var(--space-20);
  background: var(--bg-dark);
  position: relative;
}
.features::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(circle, rgba(255,255,255,.025) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none;
  opacity: .6;
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-5);
  position: relative;
}

.feature-card {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  padding: var(--space-8);
  border-radius: var(--radius-xl);
  background: var(--gradient-card);
  border: 1px solid var(--color-navy-border);
  box-shadow: var(--shadow-sm);
  transition: transform var(--ease-normal), box-shadow var(--ease-normal), border-color var(--ease-normal);
  position: relative;
  overflow: hidden;
}
.feature-card::after {
  content: '';
  position: absolute;
  inset: 0;
  background: radial-gradient(ellipse 80% 60% at 50% 110%, rgba(99,102,241,.08) 0%, transparent 65%);
  opacity: 0;
  transition: opacity var(--ease-normal);
  pointer-events: none;
}
.feature-card:hover {
  transform: translateY(-5px);
  box-shadow: var(--shadow-md), 0 0 24px rgba(99,102,241,.12);
  border-color: rgba(255,122,24,.3);
}
.feature-card:hover::after { opacity: 1; }

.feature-icon {
  width: 56px; height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-lg);
  background: rgba(255,255,255,.04);
  border: 1px solid rgba(255,255,255,.07);
  flex-shrink: 0;
  transition: background var(--ease-normal), border-color var(--ease-normal);
}
.feature-card:hover .feature-icon {
  background: rgba(255,122,24,.08);
  border-color: rgba(255,122,24,.2);
}

.feature-card h3 {
  font-size: var(--text-lg);
  font-weight: var(--fw-bold);
  color: var(--text-light);
  letter-spacing: -.02em;
}

.feature-card p {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
}

/* ============================================================
   TESTIMONIALS
   ============================================================ */
.testimonials {
  padding-block: var(--space-24);
  background: var(--color-navy-mid);
}

.testimonials-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-6);
}

.testimonial-card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: var(--space-6);
  padding: var(--space-8);
  border-radius: var(--radius-xl);
  background: var(--gradient-card);
  border: 1px solid var(--color-navy-border);
  box-shadow: var(--shadow-sm);
  transition: transform var(--ease-normal), box-shadow var(--ease-normal);
}
.testimonial-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-lg);
}

.testimonial-card blockquote p {
  font-size: var(--text-base);
  color: var(--color-text);
  line-height: var(--leading-relaxed);
  font-style: italic;
  position: relative;
}
.testimonial-card blockquote p::before {
  content: '“';
  font-size: 4rem;
  line-height: 0;
  vertical-align: -.5em;
  color: var(--color-primary);
  opacity: .4;
  margin-right: var(--space-1);
}

.testimonial-author {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding-top: var(--space-4);
  border-top: 1px solid var(--color-navy-border);
}
.testimonial-author strong { display: block; color: var(--color-white); font-size: var(--text-sm); font-weight: var(--fw-semibold); }
.testimonial-author span   { color: var(--color-text-muted); font-size: var(--text-xs); }
.testimonial-author > div  { flex: 1; }

.salary-badge {
  font-size: var(--text-xs);
  font-weight: var(--fw-bold);
  color: var(--color-accent-green);
  background: rgba(34,197,94,.1);
  border: 1px solid rgba(34,197,94,.25);
  border-radius: var(--radius-full);
  padding: var(--space-1) var(--space-3);
  flex-shrink: 0;
}

.avatar {
  border-radius: var(--radius-full);
  object-fit: cover;
  flex-shrink: 0;
  border: 2px solid var(--color-navy-border);
}

/* ============================================================
   CTA BANNER
   ============================================================ */
.cta-banner {
  background: var(--gradient-cta);
  padding-block: var(--space-20);
  position: relative;
  overflow: hidden;
}
.cta-banner::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(circle at 20% 50%, rgba(255,255,255,.08) 0%, transparent 50%),
    radial-gradient(circle at 80% 50%, rgba(0,0,0,.1) 0%, transparent 50%);
  pointer-events: none;
}

.cta-inner {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-8);
  flex-wrap: wrap;
}

.cta-inner h2 {
  font-size: var(--text-3xl);
  font-weight: var(--fw-extrabold);
  color: var(--color-white);
  letter-spacing: -.02em;
  line-height: var(--leading-tight);
}

.cta-inner p {
  font-size: var(--text-lg);
  color: rgba(255,255,255,.8);
  margin-top: var(--space-2);
}

/* ============================================================
   FOOTER
   ============================================================ */
.footer {
  background: var(--color-navy-mid);
  border-top: 1px solid var(--color-navy-border);
}

.footer-inner {
  display: grid;
  grid-template-columns: 1.5fr 1fr;
  gap: var(--space-16);
  padding-block: var(--space-16);
}

.footer-brand {
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
}
.footer-brand p {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  line-height: var(--leading-relaxed);
  max-width: 36ch;
}

.social-links {
  display: flex;
  gap: var(--space-3);
}
.social-links a {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px; height: 40px;
  border-radius: var(--radius-md);
  color: var(--color-text-muted);
  background: rgba(255,255,255,.05);
  border: 1px solid var(--color-navy-border);
  transition: color var(--ease-fast), background var(--ease-fast), transform var(--ease-fast);
}
.social-links a:hover {
  color: var(--color-white);
  background: rgba(255,107,53,.12);
  border-color: rgba(255,107,53,.3);
  transform: translateY(-2px);
}

.footer-links {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-8);
}

.footer-col h3 {
  font-size: var(--text-sm);
  font-weight: var(--fw-semibold);
  color: var(--color-white);
  letter-spacing: .04em;
  text-transform: uppercase;
  margin-bottom: var(--space-5);
}
.footer-col ul { display: flex; flex-direction: column; gap: var(--space-3); }
.footer-col a {
  font-size: var(--text-sm);
  color: var(--color-text-muted);
  transition: color var(--ease-fast);
}
.footer-col a:hover { color: var(--color-white); }

.footer-bottom {
  border-top: 1px solid var(--color-navy-border);
  padding-block: var(--space-6);
}
.footer-bottom .container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-4);
}
.footer-bottom p { font-size: var(--text-sm); color: var(--color-text-muted); }

/* ============================================================
   RESPONSIVE — Tablet (≤ 960px)
   ============================================================ */
@media (max-width: 960px) {
  :root { --container-px: var(--space-5); }

  .hero { min-height: auto; }
  .hero-inner { grid-template-columns: 1fr; gap: var(--space-12); }
  .hero-content { align-items: center; text-align: center; }
  .hero-subtext { max-width: 60ch; }
  .hero-eyebrow { margin-inline: auto; }
  .hero-actions { justify-content: center; }
  .hero-image { min-height: 340px; }
  .hero-card--offer  { left: -8px; }
  .hero-card--mentor { right: -8px; }

  .stats-grid { grid-template-columns: repeat(2, 1fr); }

  .features-grid { grid-template-columns: repeat(2, 1fr); }

  .testimonials-grid { grid-template-columns: 1fr; }

  .cta-inner { flex-direction: column; text-align: center; }

  .footer-inner { grid-template-columns: 1fr; gap: var(--space-10); }
  .footer-links { grid-template-columns: repeat(3, 1fr); }

  .nav-links, .nav-actions { display: none; }
  .hamburger { display: flex; }
}

/* ============================================================
   RESPONSIVE — Mobile (≤ 600px)
   ============================================================ */
@media (max-width: 600px) {
  :root { --container-px: var(--space-4); }

  .hero { padding-block: var(--space-16) var(--space-12); }
  .hero-image { display: none; }
  .hero-actions { flex-direction: column; align-items: stretch; }
  .hero-actions .btn { width: 100%; justify-content: center; }

  .section-title { font-size: var(--text-3xl); }

  .stats-grid { grid-template-columns: repeat(2, 1fr); gap: var(--space-4); }
  .stat-number { font-size: var(--text-4xl); }

  .features-grid { grid-template-columns: 1fr; }

  .cta-inner h2 { font-size: var(--text-2xl); }

  .footer-links { grid-template-columns: repeat(2, 1fr); gap: var(--space-6); }
  .footer-bottom .container { flex-direction: column; text-align: center; }
}

/* ============================================================
   SCROLLBAR STYLING
   ============================================================ */
::-webkit-scrollbar { width: 8px; height: 8px; }
::-webkit-scrollbar-track { background: var(--color-navy-mid); }
::-webkit-scrollbar-thumb {
  background: var(--color-navy-border);
  border-radius: var(--radius-full);
}
::-webkit-scrollbar-thumb:hover { background: rgba(255,107,53,.4); }

/* ============================================================
   SELECTION
   ============================================================ */
::selection { background: rgba(255,107,53,.3); color: var(--color-white); }

${extraRules}`;
}

export const generateCSSTool: Tool = {
  name: "generateCSS",
  description:
    "Generate a complete, premium CSS stylesheet (dark-blue/white theme, CSS variables, Flexbox + Grid, spacing system, responsive design, hover effects, shadows, gradients) matching the Scaler Academy landing page and write it to the output directory.",
  inputSchema: {
    filename: {
      type: "string",
      description: "Output filename, e.g. styles.css",
      required: true,
    },
    rules: {
      type: "string",
      description: "Optional extra CSS rules appended after the generated stylesheet.",
    },
  },

  async execute(raw: ToolInput): Promise<ToolResult> {
    if (!isGenerateCSSInput(raw)) {
      return { success: false, error: "Missing required field: filename" };
    }

    const input = raw as GenerateCSSInput;
    const extraRules = typeof input.rules === "string" && input.rules ? input.rules : "";
    const css = buildPremiumCSS(extraRules);

    return writeFileTool.execute({
      filePath: input.filename,
      content: css,
    });
  },
};
